# COMPOSE DEV
services:
  # NGINX
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod

  # API
  api:
    build:
      dockerfile: Dockerfile.prod
    volumes:
      - ./api:/api
      - /api/node_modules

  # API
  notifications:
    build:
      dockerfile: Dockerfile.prod
    volumes:
      - ./notifications-service:/notifications
      - /notifications-service/node_modules

  # CLIENT
  client:
    build:
      dockerfile: Dockerfile.prod
