services:
  # NGINX
  nginx:
    ports:
      - '80:80'
    restart: always
    image: nginx

  rabbitmq:
    image: rabbitmq:3-management
    hostname: mehouse-rabbit
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
      # - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      # - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - nginx

  # API
  api:
    restart: always
    build:
      context: ./api
    # environment:
    #   - RABBIT_HOSTNAME=rabbitmq
    env_file:
      - ./api/.env
    depends_on:
      - rabbitmq

  # API
  notifications:
    restart: always
    build:
      context: ./notifications-service
    env_file:
      - ./notifications-service/.env
    depends_on:
      - api

  # CLIENT REACT
  client:
    restart: always
    build:
      context: ./client
    environment:
      - RABBIT_HOSTNAME=rabbitmq
    env_file:
      - ./client/.env
    depends_on:
      - api

  # DATABASE
  mongodb:
    restart: always
    image: mongo
    env_file:
      - ./api/.env
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db:cached
      # - ./mongodb:/data/db

volumes:
  mongodb: null
