## FIST STAGE
FROM node:18-alpine as build

WORKDIR /api

RUN rm -rf node_modules/

# add app
COPY package*.json ./

RUN npm ci

# COPY package*.json .
COPY . ./

RUN npm run build

## SECOND STAGE
FROM node:18-alpine as start

WORKDIR /api
COPY package*.json ./

RUN npm ci --only=production

COPY --from=build /api/dist ./dist

CMD ["npm", "run", "start"]
